# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 18:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20171005_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='start_dadte',
            new_name='start_date',
        ),
    ]
