# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 21:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20171005_1533'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courses',
            new_name='Curso',
        ),
    ]
