# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 01:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20171005_1836'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Curso',
            new_name='Course',
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['name'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
    ]
